export const products = [
  {
    _id: 1,
    name: 'Nike Mercurial Superfly',
    category: 'Nike',
    image: '/images/product1.png',
    price: 320,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    _id: 2,
    name: 'Adidas Boot',
    category: 'Adidas',
    image: '/images/product2.jpg',
    price: 300,
    countInStock: 20,
    rating: 4,
    numReviews: 12,
    description: 'high quality product',
  },
  {
    _id: 3,
    name: 'Nike Mercurial Superfly',
    category: 'Nike',
    image: '/images/product3.png',
    price: 320,
    countInStock: 0,
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    _id: 4,
    name: 'Puma boot',
    category: 'Puma',
    image: '/images/product4.jpg',
    price: 260,
    countInStock: 15,
    rating: 3.5,
    numReviews: 5,
    description: 'high quality product',
  },
  {
    _id: 5,
    name: 'Nike Mercurial Superfly',
    category: 'Nike',
    image: '/images/product5.jpg',
    price: 320,
    countInStock: 5,
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
]
